../hangout.xml: hangout.xml.head hangout.xml.tail iframesubmit.js  piece_ui.js  popup_menu.js  util.js  world.js
	cat hangout.xml.head util.js popup_menu.js world.js piece_ui.js iframesubmit.js hangout.xml.tail > ../hangout.xml
